// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TalentInstitute.Infrastructure.Data;

#nullable disable

namespace TalentInstitute.Infrastructure.Migrations
{
    [DbContext(typeof(TalentInstituteDbContext))]
    [Migration("20260910005649_AddAnotaciones")]
    partial class AddAnotaciones
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TalentInstitute.Domain.Entities.Alumno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("BalanceMeritos")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NumeroMatricula")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("Alumnos", (string)null);
                });

            modelBuilder.Entity("TalentInstitute.Domain.Entities.AlumnoPace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlumnoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FechaCompletado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Materia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("PaceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("PuntajeFinal")
                        .HasColumnType("decimal(5,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("PaceId");

                    b.ToTable("AlumnoPaces", (string)null);
                });

            modelBuilder.Entity("TalentInstitute.Domain.Entities.Anotacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlumnoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("SemanaInicio")
                        .HasColumnType("date");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("StaffId");

                    b.HasIndex("AlumnoId", "SemanaInicio");

                    b.ToTable("Anotaciones", (string)null);
                });

            modelBuilder.Entity("TalentInstitute.Domain.Entities.ConfiguracionPrivilegios", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("StaffIdActualizo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UmbralActividades")
                        .HasColumnType("int");

                    b.Property<int>("UmbralActividadesRevocado")
                        .HasColumnType("int");

                    b.Property<int>("UmbralBiblioteca")
                        .HasColumnType("int");

                    b.Property<int>("UmbralBibliotecaRevocado")
                        .HasColumnType("int");

                    b.Property<int>("UmbralComedor")
                        .HasColumnType("int");

                    b.Property<int>("UmbralComedorRevocado")
                        .HasColumnType("int");

                    b.Property<int>("UmbralOficina")
                        .HasColumnType("int");

                    b.Property<int>("UmbralOficinaRevocado")
                        .HasColumnType("int");

                    b.Property<int>("UmbralPatio")
                        .HasColumnType("int");

                    b.Property<int>("UmbralPatioRevocado")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracionPrivilegios", (string)null);
                });

            modelBuilder.Entity("TalentInstitute.Domain.Entities.EntrevistaPadre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Aceptado")
                        .HasColumnType("bit");

                    b.Property<string>("Comentarios")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("ConoceADios")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaEntrevista")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombrePadre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("NumeroHijos")
                        .HasColumnType("int");

                    b.Property<bool>("RiesgoDivorcio")
                        .HasColumnType("bit");

                    b.Property<bool>("RiesgoViolencia")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("EntrevistasPadres", (string)null);
                });

            modelBuilder.Entity("TalentInstitute.Domain.Entities.Merito", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlumnoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaAplicado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRevocacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<int>("Puntos")
                        .HasColumnType("int");

                    b.Property<bool>("Revocado")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("StaffIdRevoco")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("StaffId");

                    b.ToTable("Meritos", (string)null);
                });

            modelBuilder.Entity("TalentInstitute.Domain.Entities.Meta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlumnoPaceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly>("FechaObjetivo")
                        .HasColumnType("date");

                    b.Property<int>("PaginasObjetivo")
                        .HasColumnType("int");

                    b.Property<decimal?>("PuntajeObtenido")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoPaceId");

                    b.ToTable("Metas", (string)null);
                });

            modelBuilder.Entity("TalentInstitute.Domain.Entities.Pace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Materia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<int>("PuntajeMaximo")
                        .HasColumnType("int");

                    b.Property<int>("PuntajeMinimoAprobacion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Paces", (string)null);
                });

            modelBuilder.Entity("TalentInstitute.Domain.Entities.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Staff", (string)null);
                });

            modelBuilder.Entity("TalentInstitute.Domain.Entities.Alumno", b =>
                {
                    b.OwnsOne("TalentInstitute.Domain.Entities.PrivilegeStatus", "PrivilegeStatus", b1 =>
                        {
                            b1.Property<Guid>("AlumnoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("Actividades")
                                .HasColumnType("bit")
                                .HasColumnName("Privilegio_Actividades");

                            b1.Property<bool>("Biblioteca")
                                .HasColumnType("bit")
                                .HasColumnName("Privilegio_Biblioteca");

                            b1.Property<bool>("Comedor")
                                .HasColumnType("bit")
                                .HasColumnName("Privilegio_Comedor");

                            b1.Property<bool>("Oficina")
                                .HasColumnType("bit")
                                .HasColumnName("Privilegio_Oficina");

                            b1.Property<bool>("Patio")
                                .HasColumnType("bit")
                                .HasColumnName("Privilegio_Patio");

                            b1.HasKey("AlumnoId");

                            b1.ToTable("Alumnos");

                            b1.WithOwner()
                                .HasForeignKey("AlumnoId");
                        });

                    b.OwnsOne("TalentInstitute.Domain.Entities.PrivilegiosManuales", "PrivilegiosManuales", b1 =>
                        {
                            b1.Property<Guid>("AlumnoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool?>("Actividades")
                                .HasColumnType("bit")
                                .HasColumnName("PrivilegioManual_Actividades");

                            b1.Property<bool?>("Biblioteca")
                                .HasColumnType("bit")
                                .HasColumnName("PrivilegioManual_Biblioteca");

                            b1.Property<bool?>("Comedor")
                                .HasColumnType("bit")
                                .HasColumnName("PrivilegioManual_Comedor");

                            b1.Property<bool?>("Oficina")
                                .HasColumnType("bit")
                                .HasColumnName("PrivilegioManual_Oficina");

                            b1.Property<bool?>("Patio")
                                .HasColumnType("bit")
                                .HasColumnName("PrivilegioManual_Patio");

                            b1.HasKey("AlumnoId");

                            b1.ToTable("Alumnos");

                            b1.WithOwner()
                                .HasForeignKey("AlumnoId");
                        });

                    b.Navigation("PrivilegeStatus")
                        .IsRequired();

                    b.Navigation("PrivilegiosManuales")
                        .IsRequired();
                });

            modelBuilder.Entity("TalentInstitute.Domain.Entities.AlumnoPace", b =>
                {
                    b.HasOne("TalentInstitute.Domain.Entities.Alumno", null)
                        .WithMany()
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TalentInstitute.Domain.Entities.Pace", null)
                        .WithMany()
                        .HasForeignKey("PaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TalentInstitute.Domain.Entities.Anotacion", b =>
                {
                    b.HasOne("TalentInstitute.Domain.Entities.Alumno", null)
                        .WithMany()
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TalentInstitute.Domain.Entities.Staff", null)
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TalentInstitute.Domain.Entities.Merito", b =>
                {
                    b.HasOne("TalentInstitute.Domain.Entities.Alumno", null)
                        .WithMany()
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TalentInstitute.Domain.Entities.Staff", null)
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TalentInstitute.Domain.Entities.Meta", b =>
                {
                    b.HasOne("TalentInstitute.Domain.Entities.AlumnoPace", null)
                        .WithMany()
                        .HasForeignKey("AlumnoPaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
