// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TalentInstitute.Infrastructure.Data;

#nullable disable

namespace TalentInstitute.Infrastructure.Migrations
{
    [DbContext(typeof(TalentInstituteDbContext))]
    [Migration("20260509145859_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TalentInstitute.Domain.Entities.Alumno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BalanceMeritos")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<string>("Grado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Alumnos", (string)null);
                });

            modelBuilder.Entity("TalentInstitute.Domain.Entities.AlumnoPace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlumnoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Materia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("PaceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("PaceId");

                    b.ToTable("AlumnoPaces", (string)null);
                });

            modelBuilder.Entity("TalentInstitute.Domain.Entities.EntrevistaPadre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Aceptado")
                        .HasColumnType("bit");

                    b.Property<string>("Comentarios")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("ConoceADios")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaEntrevista")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombrePadre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("NumeroHijos")
                        .HasColumnType("int");

                    b.Property<bool>("RiesgoDivorcio")
                        .HasColumnType("bit");

                    b.Property<bool>("RiesgoViolencia")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("EntrevistasPadres", (string)null);
                });

            modelBuilder.Entity("TalentInstitute.Domain.Entities.Pace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Materia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<int>("PuntajeMaximo")
                        .HasColumnType("int");

                    b.Property<int>("PuntajeMinimoAprobacion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Paces", (string)null);
                });

            modelBuilder.Entity("TalentInstitute.Domain.Entities.Alumno", b =>
                {
                    b.OwnsOne("TalentInstitute.Domain.Entities.PrivilegeStatus", "PrivilegeStatus", b1 =>
                        {
                            b1.Property<Guid>("AlumnoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("Actividades")
                                .HasColumnType("bit")
                                .HasColumnName("Privilegio_Actividades");

                            b1.Property<bool>("Biblioteca")
                                .HasColumnType("bit")
                                .HasColumnName("Privilegio_Biblioteca");

                            b1.Property<bool>("Comedor")
                                .HasColumnType("bit")
                                .HasColumnName("Privilegio_Comedor");

                            b1.Property<bool>("Oficina")
                                .HasColumnType("bit")
                                .HasColumnName("Privilegio_Oficina");

                            b1.Property<bool>("Patio")
                                .HasColumnType("bit")
                                .HasColumnName("Privilegio_Patio");

                            b1.HasKey("AlumnoId");

                            b1.ToTable("Alumnos");

                            b1.WithOwner()
                                .HasForeignKey("AlumnoId");
                        });

                    b.Navigation("PrivilegeStatus")
                        .IsRequired();
                });

            modelBuilder.Entity("TalentInstitute.Domain.Entities.AlumnoPace", b =>
                {
                    b.HasOne("TalentInstitute.Domain.Entities.Alumno", null)
                        .WithMany()
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TalentInstitute.Domain.Entities.Pace", null)
                        .WithMany()
                        .HasForeignKey("PaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
